version: '3.8'  # Specify the Docker Compose version

services:
  db:
    image: postgres:14  # Use PostgreSQL 14 image
    container_name: my_postgres  # Custom name for the container
    restart: always  # Ensure the container restarts automatically on failure
    ports:
      - "${DOCKER_POSTGRES_PORT:-5432}:5432"  # Map container port to host port, default to 5432 if not set
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}  # Password
      TZ: "Europe/Brussels"  # Set the timezone
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ab7 -d mydb"]
      interval: 10s  # Check every 10 seconds
      timeout: 5s  # Timeout after 5 seconds
      retries: 5  # Retry 5 times before considering the container unhealthy

volumes:
  postgres_data:  # Named volume to persist PostgreSQL data
